name: flutter_segment_display_example
description: Segment display example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  segment_display:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
