os:
  - linux
language: generic
addons:
  apt:
    packages:
      - libstdc++6
      - fonts-droid-fallback
cache:
  directories:
    - $HOME/.pub-cache
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor
script:
  - flutter pub get
  - flutter test
