include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    dead_code: info
    invalid_assignment: warning
  exclude:
    - "test/**"

linter:
  rules:
    lines_longer_than_80_chars: true
    prefer_single_quotes: true
